// <auto-generated />
namespace PentaStarLicenta.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedClientUserRoomIdInAccomodation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedClientUserRoomIdInAccomodation));
        
        string IMigrationMetadata.Id
        {
            get { return "201902211034126_addedClientUserRoomIdInAccomodation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
